version: '3.8'
services: 
    postgres:
        image: 'postgres:latest'
        environment: 
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=ksav
            - POSTGRES_DB=complex_fib
    redis:
        image: 'redis:latest'
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes: 
            - /app/node_modules
            - type: bind
              source: ./server
              target: /app
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=ksav
            - PGPASSWORD=password
            - PGHOST=postgres
            - PGPORT=5432
            - PGDATABASE=complex_fib
    worker:
        build: 
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes: 
            - /app/node_modules
            - type: bind
              source: ./worker
              target: /app
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
    client:
        build: 
            dockerfile: Dockerfile.dev
            context: ./client
        volumes: 
            - /app/node_modules
            - type: bind
              source: ./client
              target: /app
        stdin_open: true
    nginx:
        restart: always
        build: 
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports: 
            - '4000:80'
        depends_on: 
            - client
            - api